-- ============================================================
-- REVSHOP COMPLETE DATABASE SCHEMA
-- Oracle 10g XE Compatible
-- Clean Drop + Create Script
-- ============================================================

-- =========================
-- DROP ALL OBJECTS SAFELY
-- =========================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FAVORITES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CART CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REVIEWS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SELLERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SELLERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUCTS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORDERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORDER_ITEMS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE REVIEWS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CART_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE FAVORITES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICATIONS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =========================
-- USERS TABLE
-- =========================

CREATE TABLE USERS (
                       USER_ID NUMBER PRIMARY KEY,
                       NAME VARCHAR2(100) NOT NULL,
                       EMAIL VARCHAR2(100) UNIQUE NOT NULL,
                       PASSWORD VARCHAR2(200) NOT NULL,
                       ROLE VARCHAR2(20) NOT NULL,
                       SECURITY_QUESTION VARCHAR2(200),
                       SECURITY_ANSWER VARCHAR2(200),
                       CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

-- =========================
-- SELLERS TABLE
-- =========================

CREATE TABLE SELLERS (
                         SELLER_ID NUMBER PRIMARY KEY,
                         USER_ID NUMBER REFERENCES USERS(USER_ID),
                         BUSINESS_NAME VARCHAR2(200),
                         GST_NUMBER VARCHAR2(50)
);

CREATE SEQUENCE SELLERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SELLERS_TRG
BEFORE INSERT ON SELLERS
FOR EACH ROW
BEGIN
SELECT SELLERS_SEQ.NEXTVAL INTO :NEW.SELLER_ID FROM DUAL;
END;
/

-- =========================
-- PRODUCTS TABLE
-- =========================

CREATE TABLE PRODUCTS (
                          PRODUCT_ID NUMBER PRIMARY KEY,
                          SELLER_ID NUMBER REFERENCES SELLERS(SELLER_ID),
                          NAME VARCHAR2(200),
                          CATEGORY VARCHAR2(100),
                          DESCRIPTION VARCHAR2(500),
                          MRP NUMBER(10,2),
                          DISCOUNT_PRICE NUMBER(10,2),
                          STOCK NUMBER,
                          STOCK_THRESHOLD NUMBER
);

CREATE SEQUENCE PRODUCTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PRODUCTS_TRG
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.PRODUCT_ID FROM DUAL;
END;
/

-- =========================
-- ORDERS TABLE
-- =========================

CREATE TABLE ORDERS (
                        ORDER_ID NUMBER PRIMARY KEY,
                        USER_ID NUMBER REFERENCES USERS(USER_ID),
                        TOTAL_AMOUNT NUMBER(10,2),
                        STATUS VARCHAR2(50),
                        ORDER_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ORDERS_TRG
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
END;
/

-- =========================
-- ORDER ITEMS TABLE
-- =========================

CREATE TABLE ORDER_ITEMS (
                             ITEM_ID NUMBER PRIMARY KEY,
                             ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID),
                             PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID),
                             QUANTITY NUMBER,
                             PRICE NUMBER(10,2)
);

CREATE SEQUENCE ORDER_ITEMS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ORDER_ITEMS_TRG
BEFORE INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
SELECT ORDER_ITEMS_SEQ.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;
END;
/

-- =========================
-- REVIEWS TABLE (FIXED)
-- =========================

CREATE TABLE REVIEWS (
                         REVIEW_ID NUMBER PRIMARY KEY,
                         PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID),
                         USER_ID NUMBER REFERENCES USERS(USER_ID),
                         RATING NUMBER,
                         REVIEW_COMMENT VARCHAR2(500)
);

CREATE SEQUENCE REVIEWS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER REVIEWS_TRG
BEFORE INSERT ON REVIEWS
FOR EACH ROW
BEGIN
SELECT REVIEWS_SEQ.NEXTVAL INTO :NEW.REVIEW_ID FROM DUAL;
END;
/

-- =========================
-- CART TABLE
-- =========================

CREATE TABLE CART (
                      CART_ID NUMBER PRIMARY KEY,
                      USER_ID NUMBER REFERENCES USERS(USER_ID),
                      PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID),
                      QUANTITY NUMBER
);

CREATE SEQUENCE CART_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CART_TRG
BEFORE INSERT ON CART
FOR EACH ROW
BEGIN
SELECT CART_SEQ.NEXTVAL INTO :NEW.CART_ID FROM DUAL;
END;
/

-- =========================
-- FAVORITES TABLE
-- =========================

CREATE TABLE FAVORITES (
                           FAV_ID NUMBER PRIMARY KEY,
                           USER_ID NUMBER REFERENCES USERS(USER_ID),
                           PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE SEQUENCE FAVORITES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FAVORITES_TRG
BEFORE INSERT ON FAVORITES
FOR EACH ROW
BEGIN
SELECT FAVORITES_SEQ.NEXTVAL INTO :NEW.FAV_ID FROM DUAL;
END;
/

-- =========================
-- NOTIFICATIONS TABLE
-- =========================

CREATE TABLE NOTIFICATIONS (
                               NOTIF_ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER REFERENCES USERS(USER_ID),
                               MESSAGE VARCHAR2(500),
                               STATUS VARCHAR2(20),
                               CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE NOTIFICATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NOTIFICATIONS_TRG
BEFORE INSERT ON NOTIFICATIONS
FOR EACH ROW
BEGIN
SELECT NOTIFICATIONS_SEQ.NEXTVAL INTO :NEW.NOTIF_ID FROM DUAL;
END;
/

-- ============================================================
-- REVSHOP DEMO DATA SCRIPT
-- Run AFTER revshop_schema.sql
-- ============================================================

-- =========================
-- 1️⃣ INSERT SELLER USER
-- =========================

INSERT INTO USERS
(NAME, EMAIL, PASSWORD, ROLE, SECURITY_QUESTION, SECURITY_ANSWER)
VALUES
    ('Big C Mobiles', 'bigc@gmail.com', 'dummyhash', 'SELLER', 'Color', 'Blue');

COMMIT;

-- =========================
-- 2️⃣ INSERT SELLER RECORD
-- =========================

DECLARE
    v_user_id USERS.USER_ID%TYPE;
BEGIN
    SELECT USER_ID INTO v_user_id
    FROM USERS
    WHERE EMAIL = 'bigc@gmail.com';

    INSERT INTO SELLERS (USER_ID, BUSINESS_NAME, GST_NUMBER)
    VALUES (v_user_id, 'Big C Mobiles Pvt Ltd', '27ABCDE1234F2Z5');

    COMMIT;
END;
/

-- =========================
-- 3️⃣ INSERT 20 PRODUCTS
-- =========================

DECLARE
    v_seller_id SELLERS.SELLER_ID%TYPE;
BEGIN
    SELECT SELLER_ID INTO v_seller_id
    FROM SELLERS
    WHERE BUSINESS_NAME = 'Big C Mobiles Pvt Ltd';

    INSERT INTO PRODUCTS (SELLER_ID, NAME, CATEGORY, DESCRIPTION, MRP, DISCOUNT_PRICE, STOCK, STOCK_THRESHOLD)
    VALUES (v_seller_id, 'iPhone 15', 'Mobile', 'Apple iPhone 15 128GB', 80000, 75000, 15, 3);

    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Samsung Galaxy S24', 'Mobile', 'Samsung flagship phone', 70000, 66000, 20, 4);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'OnePlus 12', 'Mobile', 'OnePlus premium smartphone', 65000, 62000, 18, 3);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Dell Inspiron 15', 'Laptop', 'Dell 15 inch laptop', 55000, 52000, 10, 2);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'HP Pavilion', 'Laptop', 'HP gaming laptop', 75000, 72000, 8, 2);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Lenovo ThinkPad', 'Laptop', 'Business laptop', 85000, 81000, 12, 3);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Boat Airdopes 141', 'Accessories', 'Wireless earbuds', 2999, 1999, 50, 10);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Sony WH-1000XM5', 'Accessories', 'Noise cancelling headphones', 30000, 28000, 25, 5);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Apple Watch Series 9', 'Wearable', 'Apple smartwatch', 45000, 42000, 20, 4);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Samsung Galaxy Watch 6', 'Wearable', 'Samsung smartwatch', 35000, 32000, 18, 4);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'iPad Air 5', 'Tablet', 'Apple tablet 10.9 inch', 60000, 57000, 15, 3);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Samsung Tab S9', 'Tablet', 'Samsung premium tablet', 65000, 61000, 14, 3);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Logitech MX Master 3', 'Accessories', 'Wireless mouse', 9999, 8999, 40, 8);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Apple Magic Keyboard', 'Accessories', 'Apple wireless keyboard', 12000, 11000, 25, 5);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Canon EOS 1500D', 'Camera', 'DSLR camera', 50000, 47000, 10, 2);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Nikon D7500', 'Camera', 'Professional DSLR', 85000, 81000, 8, 2);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'LG 55 OLED TV', 'Electronics', '55 inch OLED TV', 120000, 115000, 6, 1);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Sony Bravia 65 TV', 'Electronics', '65 inch Smart TV', 150000, 145000, 5, 1);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Asus ROG Strix', 'Laptop', 'Gaming laptop high performance', 140000, 135000, 7, 2);
    INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, v_seller_id, 'Acer Predator Helios', 'Laptop', 'High end gaming laptop', 130000, 125000, 6, 2);

    COMMIT;
END;
/

